version: '2'
services:
  server:
    restart: always
    build:
      context: ./api
      dockerfile: ./build/Dockerfile
    ports:
      - "8000:8000"
  client:
    restart: always
    build:
      context: ./client
      dockerfile: ./build/Dockerfile
    ports:
      - "3000:3000"
  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - "6379:6379"
