apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  selector:
    matchLabels:
      app: sync
      tier: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: sync
        tier: proxy
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      #   volumeMounts:
      #   - name: nginx-volume
      #     mountPath: /etc/nginx/conf.d
      # volumes:
      #   - name: nginx-volume
      #     configMap:
      #       name: nginx-config
      #       items:
      #       - key: frontend-nginx.conf
      #         path: frontend-nginx.conf
